### ISSUE TITLE
Can't create an Either that has the same type for success and error

### ISSUE THREAD

**Issue by Yend0r** [khanage/bearded.monads#26]
The create method for either uses the type to disambiguate between the success and error case. So code such as this will not compile:

`var x = Either<string, string>.Create("hello");` <-- doesn't compile

I'm not sure if this was a design decision made on purpose?

If it is not by design then some suggestions for the change are: 

```
public static Either<Success, Error> Error(Error value) =>
            new ErrorContainer(value);
public static Either<Success, Error> Success(Success value) =>
            new SuccessContainer(value);
```
Or 
```
public static Either<Success, Error> CreateError(Error value) =>
            new ErrorContainer(value);
public static Either<Success, Error> Create(Success value) =>
            new SuccessContainer(value);
```
However, in either case (lol), the implicit operator will stop working for one of the cases. Perhaps it could work for the success case and the error case must be explicitly created? This would make the change a breaking change.

**Comment by khanage** [comment]
Hmm, that first case is definitely just an oversight, I think it'd be a good idea to `Obsolete` that create method and replace it with `Success` and `Error`.

**Comment by khanage** [comment]
The implicits can't really work - I think it would be better to throw an ambiguous type error or maybe try to create a specialised version when `Error` == `Success`. I don't know if we can express that in C# though?

**Comment by khanage** [comment]
Ok, so [this commit](https://github.com/khanage/bearded.monads/commit/bc0fe10232522c16b6e6b1d34c79e61a0fea7680) will at least allow you to use the type, but I don't think there's anyway to order the implicits. 

The only way to get that behaviour would be to drop the implicit operator for `Error`, which I don't think is worth the breaking change.

I'd accept a monomorphic `Either<A>` PR, or a PR which adds your desired behaviour to a new type in a seperate namespace, like [what has been done with unsafe option](https://github.com/khanage/bearded.monads/blob/master/Bearded.Monads/OptionUnsafe.cs).

**Comment by Yend0r** [comment]
I'm not so sure that an `Either<A>` is a good idea.  

For example, how would `map` work? You could force users to provide two mappers like this:

`public Either<NextT> Map<NextT>(Func<T, NextT> successMapper, Func<T, NextT> errorMapper) { ... }`

But that is no longer a standard `map` signature and it seems unlikely to be useful because the common usage of a map would be to change the success type and leave the error type unchanged. 

I guess you could also add a method to map to `Either<Success,Error>`:

`public Either<Success, T> MapToEither<Success>(Func<T, Success> mapper) { ... }`

But there is no way to constrain the types so that `Success != T`.

It seems like a bad idea.

**Comment by Yend0r** [comment]
Closing since the original problem is fixed.
