### ISSUE TITLE
Upgrade to DotnetCore 2.1?

### ISSUE THREAD

**Issue by Yend0r** [khanage/bearded.monads#31]
Hey, 

Would you mind if I upgrade the project to dotnet core 2.1? I can't get the tests to run locally unless I make a new test project that is 2.1 and then I have to copy them back to the existing project to commit them.

**Comment by Yend0r** [comment]
I tested and yes, if you upgrade the project then it cannot be included by .net 1.x projects. 

However, the test project can be upgraded... is that cool?

Also, FYI, Microsoft drops support for .net 1.x in July 2019, so you should be able to upgrade soon.

**Comment by khanage** [comment]
I can run the tests ok on my mac, I think you can just download a different version of dotnet and it will work?
